version: 2.1

orbs:
  python: circleci/python@1.5.0
  jq: circleci/jq@2.2.0

executors:
  pyex:
    docker:
      - image: cimg/python:3.10.2

commands:
  currnt-branch-print:
    steps:
      - run:
          name: Current branch
          command: |
            echo "current branch"
            echo << pipeline.git.branch >>
            echo << pipeline.git.revision >>
            echo ${pipeline.git.revision::6}

jobs:
  build-and-test:
    executor: pyex
    steps:
      - checkout
      - currnt-branch-print
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run main
          command: python main.py

  detect_pr:
    executor: pyex
    steps:
      - jq/install
      - run:
          name: Detect Branches
          command: |
            echo "Test pull request build"
            if [[ "$CIRCLE_PULL_REQUEST" != "" ]];
            then
              echo "# Pull request $CIRCLE_PULL_REQUEST"
            else
              echo "# Pull request not found."
            fi

workflows:
  sample:
    jobs:
      - detect_pr
      - build-and-test
