version: 2.1

orbs:
  python: circleci/python@1.5.0

executors:
  pyex:
    docker:
      - image: cimg/python:3.10.2

commands:
  currnt-branch-print:
    steps:
      - run:
          name: Current branch
          command: |
            echo "current branch"
            echo << pipeline.git.branch >>

jobs:
  build-and-test:
    executor: pyex
    steps:
      - checkout
      - currnt-branch-print
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run main
          command: python main.py

workflows:
  sample:
    jobs:
      - build-and-test
